"""
Basic pytest coverage for the critical Vault layer (engram_mcp/vault.py).

Covers:
- Discovery + 8-folder validation
- Mandatory BRAIN.md read + logging
- _safe_path traversal blocking (root + generated subdir)
- write_briefing / _write_to_generated containment + date validation (the critical bug fix)
- archive_file never-delete semantics
- read_daily_note date safety

Run: py -3.12 -m pytest tests/test_vault.py -q --tb=line
"""

from __future__ import annotations

import pytest
from pathlib import Path
import shutil
import tempfile

# Ensure we can import from src layout
import sys
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from engram_mcp.vault import Vault, VaultError, get_vault


@pytest.fixture
def minimal_vault(tmp_path: Path):
    """Create a minimal valid Brain vault structure + stub BRAIN.md for testing."""
    # Create all 8 top-level folders
    folders = {
        "capture": "00 - CAPTURE",
        "active": "01 - ACTIVE",
        "resources": "02 - RESOURCES",
        "system": "03 - SYSTEM",
        "generated": "04 - GENERATED",
        "queue": "05 - QUEUE",
        "calendar": "06 - CALENDAR",
        "archive": "07 - ARCHIVE",
    }
    for name in folders.values():
        (tmp_path / name).mkdir(parents=True, exist_ok=True)

    # GENERATED subs
    for sub in ["briefings", "summaries", "analyses", "drafts", "consolidated"]:
        (tmp_path / "04 - GENERATED" / sub).mkdir(parents=True, exist_ok=True)

    # Minimal BRAIN.md (required for read_brain_md)
    brain = tmp_path / "03 - SYSTEM" / "BRAIN.md"
    brain.write_text(
        "# BRAIN.md — Test\n\n"
        "## 1. Identity\nTest user\n\n"
        "## 4. Current Priorities\n- P1: Fix vault\n\n"
        "## 3. Active Projects\n| Engram | In progress |\n\n"
        , encoding="utf-8"
    )

    # Some daily for testing
    daily_dir = tmp_path / "01 - ACTIVE" / "daily"
    daily_dir.mkdir(exist_ok=True)
    (daily_dir / "2026-05-20.md").write_text(
        "# 2026-05-20 — Daily Note\n\n**Top 3 Today:**\n- Test vault rules\n\n## Open Loops\n- None\n",
        encoding="utf-8"
    )

    v = Vault(tmp_path)
    yield v

    # Cleanup handled by tmp_path


def test_vault_discovery_and_8_folder_validation(minimal_vault):
    v = minimal_vault
    assert (v.root / "03 - SYSTEM" / "BRAIN.md").exists()
    assert "00 - CAPTURE" in str(v.root / v.FOLDERS["capture"])


def test_read_brain_md_is_mandatory_and_logged(minimal_vault, tmp_path):
    v = minimal_vault
    content = v.read_brain_md()
    assert "BRAIN.md — Test" in content
    # Verify it logged the read (last lines of system-log)
    log = (v.root / "03 - SYSTEM" / "logs" / "system-log.md").read_text(encoding="utf-8")
    assert "read BRAIN.md (as required by POS rules" in log


def test_safe_path_blocks_traversal(minimal_vault):
    v = minimal_vault
    with pytest.raises(VaultError, match="traversal blocked"):
        v._safe_path("../../etc/passwd")
    with pytest.raises(VaultError, match="traversal blocked"):
        v._safe_path("03 - SYSTEM/../../../evil.md")


def test_write_briefing_date_validation_and_containment(minimal_vault):
    v = minimal_vault
    # Good write
    p = v.write_briefing("2026-05-22", "# Good briefing\nRules honored.")
    assert p.exists()
    assert "2026-05-22-morning.md" in str(p)
    assert "04 - GENERATED" in str(p)
    assert "briefings" in str(p)
    assert "Generated by engram-mcp" in p.read_text(encoding="utf-8")

    # Bad date (the original escape vector)
    with pytest.raises(VaultError, match="Invalid date"):
        v.write_briefing("../../evil", "bad content")

    # Bad sub via internal (defense in depth)
    with pytest.raises(VaultError, match="Invalid GENERATED subfolder"):
        v._write_to_generated("evil", "x.md", "x")

    # Evil filename
    with pytest.raises(VaultError, match="Unsafe filename"):
        v._write_to_generated("briefings", "../pwned.md", "x")


def test_archive_never_deletes(minimal_vault):
    v = minimal_vault
    # Create a temp file in CAPTURE to "archive"
    cap_file = v.root / "00 - CAPTURE" / "test-capture.md"
    cap_file.write_text("test content for archive", encoding="utf-8")
    assert cap_file.exists()

    archived = v.archive_file("00 - CAPTURE/test-capture.md", reason="test")
    assert not cap_file.exists(), "Original must be gone (moved, never deleted)"
    assert archived.exists()
    assert "07 - ARCHIVE" in str(archived)
    assert "--test-capture.md" in archived.name
    content = archived.read_text(encoding="utf-8")
    assert "test content" in content


def test_read_daily_note_safety(minimal_vault):
    v = minimal_vault
    content = v.read_daily_note("2026-05-20")
    assert "Test vault rules" in content

    with pytest.raises(VaultError, match="Invalid date"):
        v.read_daily_note("2026-05-../evil")


def test_generated_subs_enforced(minimal_vault):
    v = minimal_vault
    assert "briefings" in v.GENERATED_SUBS
    # Future writers will be forced through _write_to_generated

def test_write_brain_md_always_raises(minimal_vault):
    v = minimal_vault
    brain_before = v.get_brain_path().read_bytes()
    with pytest.raises(VaultError, match="human-gate-only"):
        v.write_brain_md("# Attempted auto-edit")
    assert v.get_brain_path().read_bytes() == brain_before


@pytest.mark.parametrize(
    "path_variant,expected_match",
    [
        ("03 - SYSTEM/BRAIN.md", "Protected path write blocked"),
        ("03 - SYSTEM\\BRAIN.md", "Protected path write blocked"),
        ("./03 - SYSTEM/BRAIN.md", "Protected path write blocked"),
        ("03 - SYSTEM//BRAIN.md", "Protected path write blocked"),
        ("03 - system/brain.md", "Protected path write blocked"),
        ("02 - RESOURCES/../03 - SYSTEM/BRAIN.md", "Unsafe relative path"),
    ],
)
def test_brain_md_write_blocked_variants(minimal_vault, path_variant, expected_match):
    v = minimal_vault
    brain_before = v.get_brain_path().read_bytes()
    with pytest.raises(VaultError, match=expected_match):
        v.write_file(path_variant, "# sneaky edit")
    assert v.get_brain_path().read_bytes() == brain_before


@pytest.mark.parametrize(
    "path_variant",
    [
        "03 - SYSTEM/BRAIN.md",
        "./03 - SYSTEM/BRAIN.md",
        "03 - SYSTEM//BRAIN.md",
        "03 - system/brain.md",
    ],
)
def test_archive_protected_brain_blocked_variants(minimal_vault, path_variant):
    v = minimal_vault
    brain_before = v.get_brain_path().read_bytes()
    with pytest.raises(VaultError, match="Protected path archive blocked"):
        v.archive_file(path_variant, reason="must-not-archive")
    assert v.get_brain_path().read_bytes() == brain_before


def test_protected_paths_derived_from_folders():
    paths = Vault.protected_paths()
    system = Vault.FOLDERS["system"]
    assert f"{system}/BRAIN.md" in paths
    assert f"{system}/logs/system-log.md" in paths


def test_system_log_write_blocked(minimal_vault):
    v = minimal_vault
    log_path = v.root / "03 - SYSTEM" / "logs" / "system-log.md"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_path.write_text("- **2026-01-01** — original entry\n", encoding="utf-8")
    before = log_path.read_bytes()
    with pytest.raises(VaultError, match="Protected path write blocked"):
        v.write_file("03 - SYSTEM/logs/system-log.md", "truncated audit log")
    assert log_path.read_bytes() == before


def test_brain_md_bak_write_blocked(minimal_vault):
    v = minimal_vault
    brain_before = v.get_brain_path().read_bytes()
    with pytest.raises(VaultError, match="Protected path write blocked"):
        v.write_file("03 - SYSTEM/BRAIN.md.bak", "# backup attempt")
    assert v.get_brain_path().read_bytes() == brain_before


def test_archive_brain_md_bak_blocked(minimal_vault):
    v = minimal_vault
    bak = v.root / "03 - SYSTEM" / "BRAIN.md.bak"
    bak.write_text("# stale backup", encoding="utf-8")
    brain_before = v.get_brain_path().read_bytes()
    with pytest.raises(VaultError, match="Protected path archive blocked"):
        v.archive_file("03 - SYSTEM/BRAIN.md.bak", reason="must-not-archive")
    assert bak.exists()
    assert v.get_brain_path().read_bytes() == brain_before


def test_system_folder_secrets_write_blocked(minimal_vault):
    v = minimal_vault
    with pytest.raises(VaultError, match="Protected path write blocked"):
        v.write_file("03 - SYSTEM/secrets.env", "API_KEY=leaked")


def test_logs_dir_write_blocked(minimal_vault):
    v = minimal_vault
    with pytest.raises(VaultError, match="Protected path write blocked"):
        v.write_file("03 - SYSTEM/logs/capture-log.md", "# fake log overwrite")


def test_write_brain_md_includes_reason(minimal_vault):
    v = minimal_vault
    with pytest.raises(VaultError, match=r"reason='weekly-review'"):
        v.write_brain_md("# x", reason="weekly-review")


def test_read_brain_md_silent_no_log(minimal_vault):
    v = minimal_vault
    v.read_brain_md(log=False)
    assert not (v.root / "03 - SYSTEM" / "logs" / "system-log.md").exists()


def test_archive_with_timestamp_alias(minimal_vault):
    v = minimal_vault
    cap_file = v.root / "00 - CAPTURE" / "alias-test.md"
    cap_file.write_text("alias content", encoding="utf-8")
    archived = v.archive_with_timestamp("00 - CAPTURE/alias-test.md", reason="alias-test")
    assert archived.exists()
    assert not cap_file.exists()


def test_get_briefing_path(minimal_vault):
    v = minimal_vault
    p = v.get_briefing_path("2026-05-22")
    assert p.name == "2026-05-22-morning.md"
    assert "briefings" in str(p)
    with pytest.raises(VaultError, match="Invalid date"):
        v.get_briefing_path("not-a-date")
